<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myfirst_xacro">

    <xacro:include filename="ros2_control.xacro" />
    <!-- <xacro:include filename="gazebo_control.xacro" /> -->

    <!-- Parameters -->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.6" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="base_mass" value="2" />

    <xacro:property name="wheel_radius" value="0.06" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="wheel_mass" value="0.2" />

    <xacro:property name="omni_wheel_radius" value="0.04" />

    <xacro:property name="lidar_radius" value="0.06" />
    <xacro:property name="lidar_width" value="0.03" />
    <xacro:property name="lidar_mass" value="0.1" />

    <xacro:property name="arm_vert_length" value="0.5" />
    <xacro:property name="arm_vert_radius" value="0.01" />
    <xacro:property name="arm_horiz_length" value="${base_width*0.4}" />
    <xacro:property name="arm_horiz_radius" value="0.01" />
    <xacro:property name="arm_mass" value="0.01" />

    <!-- Derived -->
    <xacro:property name="base_to_ground" value="${wheel_radius + base_height/2}" />
    <xacro:property name="wheel_offset_y" value="${base_width / 2}" />
    <xacro:property name="wheel_offset_x" value="${(base_length / 2) - wheel_radius}" />
    <xacro:property name="omni_x" value="${base_length / 4}" />
    <xacro:property name="omni_z" value="${base_to_ground - (base_height/2) - omni_wheel_radius}" />

    <link name="base_link">

    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="-0 0 0" />
    </joint>


    <link name="chassis">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 0.4 1.0" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${base_mass}" />
            <inertia
                ixx="${(1.0/12.0) * base_mass * (base_width*base_width + base_height*base_height)}"
                iyy="${(1.0/12.0) * base_mass * (base_length*base_length + base_height*base_height)}"
                izz="${(1.0/12.0) * base_mass * (base_length*base_length + base_width*base_width)}"
                ixy="0"
                ixz="0"
                iyz="0"
            />
        </inertial>
    </link>

    <!-- Wheel Macro -->
    <xacro:macro name="wheel" params="name parent x y z rpy axs">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 -0.005 ${wheel_width/2}" />
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1.0" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 ${wheel_width/2}" />
            </collision>
            <inertial>
                <mass value="${wheel_mass}" />
                <inertia
                    ixx="${(1.0/12.0) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                    iyy="${(1.0/12.0) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                    izz="${0.5 * wheel_mass * wheel_radius * wheel_radius}"
                    ixy="0" ixz="0" iyz="0"
                />
                <origin xyz="0 0 ${wheel_width/2}" />
            </inertial>
        </link>

        <gazebo reference="${name}">
            <mu1>1.0</mu1>
            <mu2>0.1</mu2>
            <fdir1>1 0 0</fdir1>
        </gazebo>

        <joint name="${parent}_to_${name}" type="continuous">
            <parent link="${parent}" />
            <child link="${name}" />
            <origin xyz="${x} ${y} ${z}" rpy="${rpy}" />
            <axis xyz="${axs}" />
        </joint>
    </xacro:macro>

    <!-- Lidar Macro -->
    <xacro:macro name="lidar" params="name parent x y z rpy">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder length="${lidar_width}" radius="${lidar_radius}" />
                </geometry>
                <origin xyz="0 0 ${lidar_width/2}" />
                <material name="red">
                    <color rgba="0.2 0.0 0.0 1.0" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${lidar_width}" radius="${lidar_radius}" />
                </geometry>
                <origin xyz="0 0 ${lidar_width/2}" />
            </collision>
            <inertial>
                <mass value="${lidar_mass}" />
                <inertia
                    ixx="${(1.0/12.0) * lidar_mass * (3*lidar_radius*lidar_radius + lidar_width*lidar_width)}"
                    iyy="${(1.0/12.0) * lidar_mass * (3*lidar_radius*lidar_radius + lidar_width*lidar_width)}"
                    izz="${0.5 * lidar_mass * lidar_radius * lidar_radius}"
                    ixy="0" ixz="0" iyz="0"
                />
                <origin xyz="0 0 ${lidar_width/2}" />
            </inertial>
        </link>

        <joint name="${parent}_to_${name}" type="fixed">
            <parent link="${parent}" />
            <child link="${name}" />
            <origin xyz="${x} ${y} ${z}" rpy="${rpy}" />
            <axis xyz="0 0 1" />
        </joint>

        <gazebo reference="${name}">
            <sensor name="${name}_sensor" type="gpu_lidar">
                <pose>0 0 ${lidar_width/2} 0 0 0</pose>
                <topic>${name}/scan</topic>
                <update_rate>10</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>1024</samples>
                            <resolution>1</resolution>
                            <min_angle>-3.14159265</min_angle>
                            <max_angle>3.14159265</max_angle>
                        </horizontal>
                        <vertical>
                            <samples>1</samples>
                            <resolution>0.01</resolution>
                            <min_angle>0</min_angle>
                            <max_angle>0</max_angle>
                        </vertical>
                    </scan>
                    <range>
                        <min>0.75</min>
                        <max>10.0</max>
                        <resolution>0.01</resolution>
                    </range>
                </ray>
                <always_on>1</always_on>
                <visualize>true</visualize>
            </sensor>
        </gazebo>
    </xacro:macro>

    <!-- L-Shaped Arm Macro -->
    <xacro:macro name="arm_L" params="name parent x y z rpy axis dir=1">

        <link name="${name}">

            <!-- Vertical segment -->
            <visual>
                <geometry>
                    <cylinder length="${arm_vert_length}" radius="${arm_vert_radius}" />
                </geometry>
                <origin xyz="0 0 ${arm_vert_length/2}" />
                <material name="black">
                    <color rgba="0 0 0 1.0" />
                </material>
            </visual>

            <!-- Horizontal segment -->
            <visual>
                <geometry>
                    <cylinder length="${arm_horiz_length}" radius="${arm_horiz_radius}" />
                </geometry>
                <origin xyz="0 ${dir * arm_horiz_length/2} ${arm_vert_length}"
                    rpy="1.5708 0 0" />
                <material name="black">
                    <color rgba="0 0 0 1.0" />
                </material>
            </visual>

            <!-- Collisions -->
            <collision>
                <geometry>
                    <cylinder length="${arm_vert_length}" radius="${arm_vert_radius}" />
                </geometry>
                <origin xyz="0 0 ${arm_vert_length/2}" />
            </collision>

            <collision>
                <geometry>
                    <cylinder length="${arm_horiz_length}" radius="${arm_horiz_radius}" />
                </geometry>
                <origin xyz="0 ${dir * arm_horiz_length/2} ${arm_vert_length}"
                    rpy="1.5708 0 0" />
            </collision>

            <!-- Inertial -->
            <inertial>
                <mass value="${arm_mass}" />
                <origin xyz="0 0 ${arm_vert_length/2}" />
                <inertia
                    ixx="${(1.0/12.0)*arm_mass*(3*arm_vert_radius*arm_vert_radius + arm_vert_length*arm_vert_length)}"
                    iyy="${(1.0/12.0)*arm_mass*(3*arm_vert_radius*arm_vert_radius + arm_vert_length*arm_vert_length)}"
                    izz="${0.5 * arm_mass * arm_vert_radius * arm_vert_radius}"
                    ixy="0" ixz="0" iyz="0"
                />
            </inertial>

        </link>

        <!-- Joint -->
        <joint name="${parent}_to_${name}" type="continuous">
            <parent link="${parent}" />
            <child link="${name}" />
            <origin xyz="${x} ${y} ${z}" rpy="${rpy}" />
            <axis xyz="${axis}" />
        </joint>

    </xacro:macro>


    <!-- Wheels -->
    <xacro:wheel name="lb_wheel"
        parent="chassis"
        x="${-wheel_offset_x}"
        y="${wheel_offset_y}"
        z="${-base_height/2}"
        rpy="-1.57075 0 0"
        axs="0 0 1" />
    <xacro:wheel name="rb_wheel"
        parent="chassis"
        x="${-wheel_offset_x}"
        y="${-wheel_offset_y}"
        z="${-base_height/2}"
        rpy="1.57075 0 0"
        axs="0 0 -1" />

    <xacro:wheel name="lf_wheel"
        parent="chassis"
        x="${+wheel_offset_x}"
        y="${wheel_offset_y}"
        z="${-base_height/2}"
        rpy="-1.57075 0 0"
        axs="0 0 1" />
    <xacro:wheel name="rf_wheel"
        parent="chassis"
        x="${+wheel_offset_x}"
        y="${-wheel_offset_y}"
        z="${-base_height/2}"
        rpy="1.57075 0 0"
        axs="0 0 -1" />

    <!-- Lidar -->
    <xacro:lidar name="lidar1"
        parent="chassis"
        x="0.15"
        y="0"
        z="${base_height/2}"
        rpy="0 0 0" />

    <xacro:arm_L
        name="arm1"
        parent="chassis"
        x="${base_length/2}" y="${base_width/2 - arm_vert_radius}"
        z="${-(base_height/2 - arm_vert_radius)}"
        rpy="0 1.5708 0"
        axis="0 0 1"
        dir="-1"
    />

    <xacro:arm_L
        name="arm2"
        parent="chassis"
        x="${base_length/2}" y="${-(base_width/2 - arm_vert_radius)}"
        z="${-(base_height/2 - arm_vert_radius)}"
        rpy="0 1.5708 0"
        axis="0 0 1"
    />

</robot>